line: bda2 # the cdn upload line
limit: 5 # the limit of video upload threads
streamers:
  patterns-example: # the pattern matching(WIP, you can ignore this field and just leave it as this example)
    copyright: 1 # the copyright of video (1 for original, 2 for reprint)
    source: https://live.bilibili.com/xxxxxxxx # the source of video (if your video is re-print)
    tid: 138 # the type id of video
    cover: '' # the cover of video (if you want to customize, set it as the path to your cover image)
    title: "your video title"
    desc_format_id: 0
    desc: "your video description"
    dynamic: '' # the dynamic information of video
    tag: "your, video, tags" # the tags of video, separated by comma